### ISSUE TITLE
获取最近一条动态截图会获取到置顶动态

### ISSUE THREAD

**Issue by a6513375** [uyoungco/puppeteer-bilibili-up-dynamic#1]
如题
被截图用户的主页存在置顶动态的话，返回数据就只会为置顶动态

**Comment by uyoungco** [comment]
好的 我有空会去修一下，最近年前加班有点严重

**Comment by uyoungco** [comment]
其实你可以用接口获取最近一条动态ID，然后用ID来获取截图

**Comment by a6513375** [comment]
> 其实你可以用接口获取最近一条动态ID，然后用ID来获取截图

好） 那有办法让截图的动态自动展开吗

**Comment by uyoungco** [comment]
> > 你可以用接口获取最近的动态ID，然后用ID来获取截图
> 
> 好）那有办法让的动态自动展开吗
通过ID获取的动态是展开的，我一直都用这个方式

**Comment by uyoungco** [comment]
> > 其实你可以用接口获取最近一条动态ID，然后用ID来获取截图
> 
> 好） 那有办法让截图的动态自动展开吗

我会尽力的!~

**Comment by uyoungco** [comment]
@a6513375 问题修复了
